apps/comentarios/urls.py
from django.urls import path, include
from . import views

app_name = 'comentarios'

urlpatterns = [
    path('crear/<int:pk>', views.crear, name = 'crear'),
    path('editar/<int:pk>', views.editar.as_view(), name = 'editar'),
    path('eliminar/<int:pk>', views.eliminar.as_view(), name = 'eliminar')
]

apps/publicaciones/urls.py
from django.urls import path, include
from . import views

app_name = 'publicaciones'

urlpatterns = [
    # READ DEL CRUD (TODAS LAS PUBLICACIONES)
    # 127.0.0.1:8000/publicaciones/
    path('', views.home, name='home'),

    # READ DEL CRUD (UNA PUBLICACION ESPECIFICA)
    # 127.0.0.1:8000/publicaciones/mostrar/1
    path('mostrar/<int:pk>', views.mostrar, name='mostrar'),
    
    # CREATE DEL CRUD.(CREAR UNA PUBLICACION)
    # 127.0.0.1:8000/publicaciones/crear
    path('crear/', views.crear, name='crear'),

    # UPDATE DEL CRUD (EDITAR UNA PUBLICACION ESPECIFICA)
    # 127.0.0.1:8000/publicaciones/editar/1
    path('editar/<int:pk>', views.editar.as_view(), name='editar'),

    # DELETE DEL CRUD (ELIMINAR UNA PUBLICACION ESPECIFICA)
    # 127.0.0.1:8000/publicaciones/eliminar/1
    path('eliminar/<int:pk>', views.eliminar.as_view(), name='eliminar'),
]

proyectoDjango/urls.py
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('contacto',views.contacto,name='contacto'),
    path('sobrenosotros',views.sobreNosotros,name='sobreNosotros' ),

    # APPS

    path('publicaciones/', include('apps.publicaciones.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('comentarios/', include('apps.comentarios.urls')),

    #LOGIN Y LOGOUT
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/publicaciones/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):

    nombre = models.CharField(max_length=50)

    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

class Publicacion(models.Model):

    usuario = models.ForeignKey(User, on_delete = models.CASCADE)

    titulo = models.CharField(max_length=250)

    imagen = models.ImageField(upload_to = 'publicaciones')

    contenido = models.TextField()

    categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)

    fechaCreacion = models.DateTimeField(
        'Creado',
        auto_now_add = True
    )

    fechaEdicion = models.DateTimeField(
        'Modificado',
        auto_now = True
    )

    def __str__(self):
        return self.titulo

apps/publicaciones/forms.py
from django import forms
from .models import Publicacion

class FormularioPublicar(forms.ModelForm):

    class Meta:

        model = Publicacion
        fields = ['titulo','contenido','imagen','categoria']

class FormularioEditar(forms.ModelForm):

    class Meta:

        model = Publicacion
        fields = ['titulo','contenido','imagen','categoria']

apps/publicaciones/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy

from .models import Publicacion,Categoria
from .forms import FormularioPublicar, FormularioEditar

from apps.comentarios.models import Comentario

#CONTROLA SI EL USUARIO ESTA LOGEADO EN UNA VISTA BASADA EN CLASES
from django.contrib.auth.mixins import LoginRequiredMixin
#CONTROLA SI EL USUARIO ESTA LOGEADO EN UNA VISTA BASADA EN FUNCIONEs
from django.contrib.auth.decorators import login_required

#CONTROLA QUE EL USUARIO SEA STAFF VISTA BASADA EN FUNCION
from django.contrib.admin.views.decorators import staff_member_required
#CONTROLA QUE EL USUARIO SEA STAFF PARA VISTA BASADA EN CLASE
from django.contrib.auth.mixins import UserPassesTestMixin

# Create your views here.

def home(request):
    categoria = request.GET.get('categoria',None)
    orden = request.GET.get('orden',None)
    publicaciones = Publicacion.objects.all()
    publicaciones = publicaciones.order_by('-fechaCreacion')
    categorias = Categoria.objects.all()

    if orden == 'a':
        publicaciones = publicaciones.order_by('titulo')
    elif orden == 'z':
        publicaciones = publicaciones.order_by('-titulo')
    elif orden == 'nuevo':
        publicaciones = publicaciones.order_by('-fechaCreacion')
    elif orden == 'antiguo':
        publicaciones = publicaciones.order_by('fechaCreacion')
    
    if categoria != None:
        publicaciones = publicaciones.filter(categoria = categoria)
    
    contexto = {'publicaciones': publicaciones,'categorias':categorias}
    
    return render(request, 'publicaciones/home.html', contexto)

def mostrar(request, pk):
    publicacion = Publicacion.objects.get(pk = pk)
    contexto = {}
    contexto['publicacion'] = publicacion

    comentario = Comentario.objects.filter(publicacion = publicacion)
    contexto['comentarios'] = comentario.order_by('-fechaCreacion')
    return render(request, 'publicaciones/mostrar.html', contexto)

@login_required
def crear(request):
    categorias = Categoria.objects.all()

    if request.method == 'POST':
        formulario = FormularioPublicar(request.POST, request.FILES)
        if formulario.is_valid():
            titulo = formulario.cleaned_data['titulo']
            imagen = formulario.cleaned_data['imagen']
            contenido = formulario.cleaned_data['contenido']
            categoria = formulario.cleaned_data['categoria']
            Publicacion.objects.create(
                usuario=request.user,
                titulo=titulo,
                imagen=imagen,
                contenido=contenido,
                categoria=categoria
            )
            return HttpResponseRedirect(reverse_lazy('publicaciones:home'))
    else:
        formulario = FormularioPublicar()

    contexto = {'categorias': categorias, 'formulario': formulario}
    return render(request, 'publicaciones/crear.html', contexto)

class editar(LoginRequiredMixin,UpdateView):
    model = Publicacion
    template_name = 'publicaciones/editar.html'
    form_class = FormularioEditar
    success_url = reverse_lazy('publicaciones:home')

class eliminar(LoginRequiredMixin,DeleteView):
    model = Publicacion
    success_url = reverse_lazy('publicaciones:home')

templates/publicaciones/crear.html
{% extends 'base.html' %}

{% load static %}

{% block contenido %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'img/publicaciones/home.png' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Crear publicación</h1>
                    <span class="subheading">Aportá tu granito de arena</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Rellená los campos necesarios para compartir tu publicación</p>
                <div class="my-5">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Título: <input type="text" name="titulo" id="titulo"></p>
                        <p>Imagen: <input type="file" name="imagen" id="imagen"></p>
                        <p>
                            Categoría:
                            <select id="categoria" name="categoria">
                                {% for categoria in categorias %}
                                <option value="{{categoria.pk}}">{{categoria.nombre}}</option>
                                {% endfor %}
                            </select>
                        </p>
                        <p>Contenido: <textarea name="contenido" id="contenido"></textarea></p>
                        <p><input type="submit" value="Crear"></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock contenido %}

templates/publicaciones/editar.html
{% extends 'base.html' %}

{% load static %}

{% block contenido %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'img/publicaciones/home.png' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Editar publicación</h1>
                    <span class="subheading">Aportá tu granito de arena</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Rellená los campos necesarios para editar tu publicación.</p>
                <div class="my-5">
                    <form action ="{% url 'publicaciones:editar' publicacion.pk %}" method="post" enctype="multiplart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="submit" value="Confirmar">
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock contenido %}

templates/publicaciones/home.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %} El Cambio Climático - Publicaciones {% endblock titulo %}

{% block contenido %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'img/publicaciones/home.png' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Publicaciones</h1>
                    <span class="subheading">De personas para personas</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">

            <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #cefdc0be;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'home' %}">
                        <img src="{% static 'img/planetita.ico' %}" alt="Bootstrap" width="30" height="34">
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="?orden=nuevo"><strong>Nuevo</strong></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="?orden=antiguo"><strong>Antiguo</strong></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="?orden=a"><strong>A..Z</strong></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="?orden=z"><strong>Z..A</strong></a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    <strong>Categorias</strong>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="?">TODAS</a></li>
                                    {% for categoria in categorias %}
                                    <li><a class="dropdown-item"
                                            href="?categoria={{categoria.pk}}">{{categoria.nombre}}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            {% for publicacion in publicaciones %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'publicaciones:mostrar' publicacion.pk %}">
                    <h2 class="post-title">{{publicacion.titulo}}</h2>
                    <p><img src="{{publicacion.imagen.url}}" style="width:50%"></p>
                </a>
                <p class="post-meta">
                    Publicado por 
                    <strong>{{publicacion.usuario}}</strong>
                    en {{publicacion.fechaCreacion.date}}
                    - {{publicacion.categoria}}
                    <br>
                    {% if request.user.is_authenticated and request.user.is_staff or request.user == publicacion.usuario %}
                    <a href="{% url 'publicaciones:editar' publicacion.pk %}"> Editar </a>
                    |
                    <a href="{% url 'publicaciones:eliminar' publicacion.pk %}"> Eliminar </a>
                    |
                    {% endif%}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}
        </div>
    </div>
</div>


{% endblock contenido %}

templates/publicaciones/mostrar.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %} El Cambio climático - Publicación {% endblock titulo %}

{% block contenido %}

<!-- Page Header-->
<header class="masthead" style="background-image: url({{ publicacion.imagen.url }})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{publicacion.titulo}}</h1>
                    <span class="meta">
                        Publicado por
                        <a href="#!">{{publicacion.usuario}}</a>
                        el {{publicacion.fechaCreacion}}
                        <br><br>
                        {% if request.user.is_authenticated and request.user.is_staff or request.user == publicacion.usuario %}
                            <a href="{% url 'publicaciones:editar' publicacion.pk %}"> Editar </a>
                            |
                            <a href="{% url 'publicaciones:eliminar' publicacion.pk %}"> Eliminar </a>
                            |
                        {% endif%}
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>{{publicacion.contenido}}</p>
                <!-- Divider-->
                <hr class="my-4" />
                <h3> Comentarios </h3>
            </div>
        </div>
    </div>
</article>


<!-- Mostrar los comentarios -->

<section>
    {% for comentario in comentarios %}
    <div class="cajaComentarios_container">
        <div class="cajaComentarios_comentario">
            <div class="cajaComentarios_titulo">
                <div class="__usuario">@{{comentario.usuario}}</div>
                <div class="__fecha">{{comentario.fechaEdicion.date}}</div>
            </div>
            <div class="cajaComentarios_contenido">{{comentario.contenido}}</div>
        </div>
        {% if request.user.is_authenticated and request.user.is_staff or request.user == comentario.usuario %}
            <div class="cajaComentarios_botones">
                <a href="{% url 'comentarios:editar' comentario.pk %}">Editar</a><a
                    href="{% url 'comentarios:eliminar' comentario.pk %}">Eliminar</a>
            </div>
        {% endif %}
    </div>
    {% endfor %}

    <!-- Crear un comentario.  -->
    {% if request.user.is_authenticated %}

    <form action="{% url 'comentarios:crear' publicacion.pk %}" method="post" class="formComentarios">
        {% csrf_token %}
        <label for="comentario" class="__titulo">Agregá un comentario: </label>
        <div class="__container">
            <input type="text" name="comentario" id="comentario" class="__campoInput">
            <input type="submit" value="Comentar" class="__botonSubmit">
        </div>
    </form>
    {% endif %}
</section>


{% endblock contenido %}

templates/publicaciones/publicacion_confirm_delete.html
{% extends 'base.html' %}

{% block contenido %}
<br><br><br><br>

<div class="card text-center">
    <div class="card-header">
        ELIMINAR PUBLICACIÓN
    </div>
    <div class="card-body">
        <form method="post">
            <h5 class="card-title">¡ADVERTENCIA!</h5>
            <p class="card-text">¿Estás seguro que desea eliminar esta publicación: "{{ object }}" ?</p>
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Eliminar" class="btn btn-danger">
        </form>
    </div>
    <div class="card-footer text-body-secondary">
        Si eliminas esta publicación, no podrás volver a recuperarlo.
    </div>
</div>

{% endblock contenido %}