apps/publicaciones/urls.py
from django.urls import path, include
from . import views

app_name = 'publicaciones'

urlpatterns = [
    # READ DEL CRUD (TODAS LAS PUBLICACIONES)
    # 127.0.0.1:8000/publicaciones/
    path('', views.home, name='home'),

    # READ DEL CRUD (UNA PUBLICACION ESPECIFICA)
    # 127.0.0.1:8000/publicaciones/mostrar/1
    path('mostrar/<int:pk>', views.mostrar, name='mostrar'),
    
    # CREATE DEL CRUD.(CREAR UNA PUBLICACION)
    # 127.0.0.1:8000/publicaciones/crear
    path('crear/', views.crear, name='crear'),

    # UPDATE DEL CRUD (EDITAR UNA PUBLICACION ESPECIFICA)
    # 127.0.0.1:8000/publicaciones/editar/1
    path('editar/<int:pk>', views.editar.as_view(), name='editar'),

    # DELETE DEL CRUD (ELIMINAR UNA PUBLICACION ESPECIFICA)
    # 127.0.0.1:8000/publicaciones/eliminar/1
    path('eliminar/<int:pk>', views.eliminar.as_view(), name='eliminar'),
]

apps/usuarios/urls.py
from django.urls import path, include
from . import views

app_name = 'usuarios'

urlpatterns = [

    path('registro/', views.Registro.as_view(), name="registro"),

]

proyectoDjango/urls.py
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('contacto',views.contacto,name='contacto'),
    path('sobrenosotros',views.sobreNosotros,name='sobreNosotros' ),

    # APPS

    path('publicaciones/', include('apps.publicaciones.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('comentarios/', include('apps.comentarios.urls')),

    #LOGIN Y LOGOUT
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> {% block titulo %} {% endblock titulo %} </title>
        <link rel="icon" type="image/x-icon" href="{% static 'img/planetita.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'css/comentarios.css' %}">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home' %}">El Cambio Climático</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'sobreNosotros' %}">Nosotros</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'publicaciones:home' %}">Publicaciones</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'contacto' %}">Contacto</a></li>

                        {% if user.is_authenticated %}      
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4">Bienvenidx {{user}}</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'publicaciones:crear' %}">CREAR PUBLICACIÓN</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4">Bienvenidx, visitante</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'usuarios:registro' %}">Registro</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block contenido %} {% endblock contenido %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="small text-center text-muted fst-italic">
                            El Cambio Climático &copy; 2023 <br>
                            Este proyecto fue desarrollado por... <br>
                            <a href="https://instagram.com/ariadnasandoval">Ariadna Sandoval</a>
                            |
                            <a href="https://instagram.com/mrtnp_">Martina Piedrabuena</a>
                            |
                            <a href="https://instagram.com/lauty_mananes">Lautaro Mañanes</a>
                            |
                            <a href="https://instagram.com/marezeflo">Mariano Flores</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/contacto.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %} El Cambio Climático - Contacto {% endblock titulo %}

{% block contenido %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'img/contacto.png' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>Contáctanos</h1>
                            <span class="subheading">¿Algo que contar? Te escuchamos</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>
                            Si querés comunicarte por algún motivo con nosotros te dejamos los medios necesarios para que puedas dejarnos un mensaje a cada uno de los integrantes.
                        </p>
                        <ul style="font-size:1.25em">
                            <li>Ariadna Sandoval <a href="https://github.com/ariadnasandoval"><img src="{% static 'img/github.png' %}" style="height:1em"></a> <a href="https://instagram.com/ariadnasandoval"><img src="{% static 'img/instagram.png' %}" style="height:1em"></a> <a href="mailto:ariadnasandoval@gmail.com"><img src="{% static 'img/gmail.png' %}" style="height:1em"></a></li>
                            <li>Martina Piedrabuena <a href="https://github.com/MartinaPiedrabuena"><img src="{% static 'img/github.png' %}" style="height:1em"></a> <a href="https://instagram.com/mrtnp_"><img src="{% static 'img/instagram.png' %}" style="height:1em"></a> <a href="mailto:piedrabuenam21@gmail.com"><img src="{% static 'img/gmail.png' %}" style="height:1em"></a></li>
                            <li>Lautaro Mañanes <a href="https://github.com/lauttymananes"><img src="{% static 'img/github.png' %}" style="height:1em"></a> <a href="https://instagram.com/lauty_mananes"><img src="{% static 'img/instagram.png' %}" style="height:1em"></a> <a href="mailto:lau16mananes@gmail.com"><img src="{% static 'img/gmail.png' %}" style="height:1em"></a></li>
                            <li>Mariano Flores <a href="https://github.com/marezeflo"><img src="{% static 'img/github.png' %}" style="height:1em"></a> <a href="https://instagram.com/marezeflo"><img src="{% static 'img/instagram.png' %}" style="height:1em"></a> <a href="mailto:marezeflo@gmail.com"><img src="{% static 'img/gmail.png' %}" style="height:1em"></a></li>
                        </ul>
                        <br>
                        <img src="{% static 'img/informatorio.png' %}" style="width:100%">
                    </div>
                </div>
            </div>
        </main>

{% endblock contenido %}

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %} El Cambio Climático - Home {% endblock titulo %}

{% block contenido %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'img/home.png' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>El Cambio Climático</h1>
                    <span class="subheading">Cambio de mentalidad: Inspirando hoy, protegiendo el mañana</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h2 style="font-weight: 600">
                    Bienvenido a nuestro blog, aquí encontrarás diversas publicaciones relacionadas al cambio climático y todo lo que lo refiere. Noticias, opiniones, ideas, proyectos, campañas, desastres naturales e iniciativas cívicas. Lo bueno, lo malo, lo necesario para concientizar, está aquí.
                </h2>
                <hr class="my-4" />
                <h3> Estas son nuestras últimas publicaciones...</h3>
                {% for publicacion in ultimasTresPublicaciones %}
                <!-- Post preview-->
                <hr class="my-4" />
                <div class="post-preview">
                    <a href="{% url 'publicaciones:mostrar' publicacion.pk %}">
                        <h2 class="post-title">{{publicacion.titulo}}</h2>
                        <p><img src="{{publicacion.imagen.url}}" style="width:100%"></p>
                    </a>
                    <p class="post-meta">
                        Publicado por
                        <strong>{{publicacion.usuario}}</strong>
                        el {{publicacion.fechaCreacion}}
                        <br>
                        {% if request.user.is_authenticated and request.user.is_staff or request.user == publicacion.usuario %}
                            <a href="{% url 'publicaciones:editar' publicacion.pk %}"> Editar </a>
                            |
                            <a href="{% url 'publicaciones:eliminar' publicacion.pk %}"> Eliminar </a>
                            |
                        {% endif%}
                    </p>
                </div>
                {% endfor %}
                <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'publicaciones:home' %}">Más publicaciones</a></div>
            </div>
        </div>
    </div>

</main>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="../static/js/scripts.js"></script>

{% endblock contenido %}

templates/sobrenosotros.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %} El Cambio Climático - Sobre nosotros {% endblock titulo %}

{% block contenido %}

<!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'img/sobrenosotros.png' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>¿Quienes somos?</h1>
                            <span class="subheading">Conocenos...</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>
                            Somos un grupo de programadores avocados al cambio climático y cómo afecta esto en nuestras vidas.
                            Queremos aportar nuestro grano de arena y dar un lugar para que se conozcan las distintas realidades que convergen en nuestro objetivo, concientizar.
                        </p>
                        <p>Este grupo se compone por...</p>
                        <ul>
                            <li>Ariadna Sandoval</li>
                            <li>Martina Piedrabuena</li>
                            <li>Lautaro Mañanes</li>
                            <li>Mariano Flores</li>
                        </ul>
                        <p>
                            Nuestra capacitación como desarrolladores se la debemos al
                            <a href="https://www.instagram.com/chacotec_/">Informatorio Chaco</a>
                            acompañado por la
                            <a href="https://empleo.chaco.gob.ar/informatorio/">Subsecretaría de Empleo del Chaco</a>.
                        </p>
                        <br>
                        <img src="{% static 'img/informatorio.png' %}" style="width:100%">
                    </div>
                </div>
            </div>
        </main>

{% endblock contenido %}